Stat svc
PetrutikSA/java-explore-with-me pull request #1
Opened 2024-10-03 16:58 UTC by PetrutikSA

ТЗ зделал, в постмане проверил рабуту сервиса статистики. Тестов написал минимум, потом дополню, пока что не хочу дольше задерживать срок сдачи первой итерации. Клиент статистики написл с помощью RestClient. Тестировать с помосшью @RestTestClient не получается, т.к. он завязан на котентесте Boot-a, а данный модуль проекта по сути библиотека, которая будет просто использоваться главным сервсом, поэтому покрою тестами уже в месте с главным сервисом.

2024-10-04 10:26 UTC, afomkina requested changes

2024-10-04 10:26 UTC, afomkina commented on stats/stats-client/src/main/java/ru/practicum/StatsClient.java
> +                .baseUrl("http://localhost:9090")
Base url лучше вынести в константу

2024-10-04 10:26 UTC, afomkina commented on stats/stats-client/pom.xml
> +            <artifactId>lombok</artifactId>
В данном модуле lombok не используется, зависимость лучше удалить

2024-10-04 10:26 UTC, afomkina commented on stats/stats-server/src/main/java/ru/practicum/model/App.java
> +@Data
Использование `@Data` в jpa-сущностях приводит к [вот этой проблеме](https://habr.com/ru/company/haulmont/blog/564682/)

Нужно удалить аннотацию из всех jpa-сущностей

2024-10-04 12:22 UTC, PetrutikSA commented
Исправил

2024-10-05 11:17 UTC, afomkina approved these changes

2024-10-07 08:34 UTC, merged