Main svc
PetrutikSA/java-explore-with-me pull request #2
Opened 2024-10-15 11:39 UTC by PetrutikSA

Тз сделал, тесты постмана проходят.
Тестами обложил по сути только на валидацию, т.к. временимало а это задание со звездокой решил остановиться на этом и дольше проверял через постман.
В Dto UpdateEventUserRequest в отличие от UpdateEventAdminRequest не испльзовал аннотацию @AfterCurrentTimeBy(hours = 2) для валидации из за тестов в постмане, в нем дата захардкодина на 11 октября, и тесты падают на валидации а не на Конфликте как ожидается, поэтому данную логику пришлось перенести в сервис.

2024-10-16 16:20 UTC, afomkina requested changes

2024-10-16 16:20 UTC, afomkina commented on ewm-service/src/main/java/ru/practicum/compilation/repository/CompilationRepository.java
> +    Page<Compilation> findAllByPinned(Boolean pinned, Pageable pageable);
Объект `Page` никак не используется, кроме как кастуется в лист, можно сразу вернуть `List<Compilation>` и избежать кастов. Поправь и в других репозиториях

2024-10-16 16:20 UTC, afomkina commented on ewm-service/src/main/java/ru/practicum/category/controller/CategoryAdminController.java
> +        statsClient.createRecord(new EndpointHitDto(APP_NAME, request.getRequestURI(), request.getRemoteAddr()));
Данный метод должен вызываться только при создании ивентов, нужно удалить лишнее создание записей здесь и в других классах

2024-10-16 16:20 UTC, afomkina commented on ewm-service/src/main/java/ru/practicum/category/controller/CategoryAdminController.java
> +    public CategoryDto createCategory(@RequestBody @Valid NewCategoryDto newCategoryDto, HttpServletRequest request) {
Поля `HttpServletRequest request` в параметрах метода быть не должно, пользователь не будет передавать эти данные. Убери и в других контроллерах

2024-10-16 16:20 UTC, afomkina commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryAdminServiceBase.java
> +        Category category = findCategoryByIdOrThrowNotFoundException(categoryId);
Объявлять переменную не нужно, так как она нигде больше не используется

2024-10-16 16:20 UTC, afomkina commented on ewm-service/src/main/java/ru/practicum/dto/location/LocationMapper.java
> +    LocationDto locationToLocationDto(Location location);
Методы со строк 14 и 16 нигде не используются

2024-10-16 16:20 UTC, afomkina commented on ewm-service/src/main/java/ru/practicum/dto/location/LocationMapper.java
Все мапперы стоит вынести в отдельный от dto пакет

2024-10-16 16:20 UTC, afomkina commented on ewm-service/src/main/java/ru/practicum/event/controller/EventPublicController.java
> +public class EventPublicController {
Только в этом классе должны остаться `HttpServletRequest request` в параметрах запроса и вызов метода `statsClient.createRecord`

2024-10-16 16:20 UTC, afomkina commented on ewm-service/src/main/java/ru/practicum/event/repository/EventRepository.java
> +    Optional<Event> findByIdAndInitiatorId(Long id, Long initiatorId);
Метод нигде не используется

2024-10-16 16:20 UTC, afomkina commented on ewm-service/src/main/java/ru/practicum/event/service/EventAdminServiceBase.java
> +        if (rangeStartString != null && !rangeStartString.isBlank()) {
Код со строк 65-72 повторяется в классе `EventPublicServiceBase` на строках 59-66, нужно его вынести в отдельный метод и переиспользовать

2024-10-16 16:20 UTC, afomkina commented on ewm-service/src/main/java/ru/practicum/event/service/EventAdminServiceBase.java
> +        LocationDto newLocationDto = updateEventAdminRequest.getLocation();
Код со строк 94-101 повторяется на строках 104-111 класса  `EventPrivateServiceBase`. Нужно его переиспользовать

2024-10-16 16:20 UTC, afomkina commented on ewm-service/src/test/java/ru/practicum/category/TestObjectsCategory.java
Здорово, что написал тесты 🔥 Они получились отличными

2024-10-16 16:20 UTC, afomkina commented on ewm-service/src/test/java/ru/practicum/event/controller/EventPrivateControllerTest.java
> +//    void updateWrongStateEventByUserGetBadRequest() throws Exception {
Закомментированный код нужно удалять

2024-10-16 17:26 UTC, PetrutikSA commented on ewm-service/src/main/java/ru/practicum/dto/location/LocationMapper.java
> +    LocationDto locationToLocationDto(Location location);
Они используется в EventMaperImpl когда он генерируется Mapstruct-ом

2024-10-16 18:12 UTC, PetrutikSA commented
Исправил

2024-10-17 13:44 UTC, afomkina approved these changes
Получилась отличнаяя основная часть! Код выглядит чисто и оптимально

2024-10-17 13:56 UTC, merged